<a href="https://colab.research.google.com/github/dhsprojects/advancepython/blob/master/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 # i am going to work with tensorflow

* Introduction
* Getting information from tensors
* Manipulating Tensors
* Using @tf.function (a way to speed upyour regular python function)
* Using GPU with tensorflow
* Exercises to try for yourself

In [ ]:
import tensorflow as tf
import numpy as np
tf.__version__        

'2.5.0'

In [ ]:
#create tf constants
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check number of dim in tensorflow
scaler.ndim

0

In [ ]:
#create vector
vector = tf.constant([10,20])
vector 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#create matrix
matrix = tf.constant([[10,20],
                     [30,40]])

In [ ]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                      [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
#tensorflow variable
changeable_tensor = tf.Variable([1,2])
unchangeable_tensor = tf.constant([5,10])

In [ ]:
#changeing value in Changeable
changeable_tensor[0].assign(7,)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 2], dtype=int32)>

In [ ]:
#random number generator
random_1 = tf.random.Generator.from_seed(7)
random_2 = random_1.normal(shape = (3,2))
random_3 = tf.random.Generator.from_seed(7)
random_4 = random_3.normal(shape = (3,2))

random_1,random_2,random_3,random_4,random_2 == random_4

(<tensorflow.python.ops.stateful_random_ops.Generator at 0x7fa8b4c387d0>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Shuffle the matrix or tensor

In [ ]:
#shullfle the matrix
not_suffled = tf.constant([[1,2],
                           [3,4],
                           [5,6]])
not_suffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_suffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

In [ ]:
#A Python integer. Used to create a random seed for the distribution
not_suffled1 = tf.constant([[1,2,3],
                            [4,5,6],
                            [7,8,9],
                            [10,11,12]])
not_suffled1

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_suffled1,seed=42)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 4,  5,  6]], dtype=int32)>

In [ ]:
tf.random.set_seed = 42  # global level randomseed
tf.random.shuffle(not_suffled1,seed = 42)  #operation level ramdom seed

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 4,  5,  6],
       [10, 11, 12],
       [ 7,  8,  9],
       [ 1,  2,  3]], dtype=int32)>

In [ ]:
#uniform distribution
uniform = tf.random.uniform(shape=(3,2),minval = 5,maxval= 50, dtype=tf.int32) 

In [ ]:
uniform

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6, 33],
       [13, 26],
       [39, 30]], dtype=int32)>

In [ ]:
tf1 = tf.random_uniform_initializer(
    minval=-0.05, maxval=0.05, seed=None
)

In [ ]:
tf1

In [ ]:
#coverting numpy into tensor
import numpy as np
numpy_A = np.arange(1,25,dtype = np.int32)
numpy_A

#tensorflow.constant(matrix)
#tf.constant(vector)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A,shape=(2,3,4))
B = tf.constant(numpy_A)

A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
tf_rank_4 = tf.zeros(shape = (2,3,4,5),dtype= tf.int32)

In [ ]:
tf_rank_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]], dtype=int32)>

In [ ]:
tf_rank_4.shape,tf_rank_4.ndim,tf.size(tf_rank_4),tf.size(tf_rank_4).numpy()

(TensorShape([2, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>,
 120)

In [ ]:
print("Element in the 0 axis:",tf_rank_4.shape[0])

Element in the 0 axis: 2


In [ ]:
print("Element in the last axis",tf_rank_4.shape[-1])

Element in the last axis 5


### Tensor Indexing
#### its similar to python list.





In [ ]:
l1 = [1,2,3,4]
l1[:2]

[1, 2]

In [ ]:
#getting first two elements for every matrix
tf_rank_4[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]]], dtype=int32)>

## Get the first element  from each dimension from each index for the final one

In [ ]:
tf_rank_4[:1,:1,:1,],tf_rank_4[:1,:1,:1,:]

(<tf.Tensor: shape=(1, 1, 1, 5), dtype=int32, numpy=array([[[[0, 0, 0, 0, 0]]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 1, 1, 5), dtype=int32, numpy=array([[[[0, 0, 0, 0, 0]]]], dtype=int32)>)

In [ ]:
tf_rank_4[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=int32, numpy=
array([[[[0],
         [0],
         [0],
         [0]]]], dtype=int32)>

In [ ]:
tf_rank_4[:1,:,:1,:1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=int32, numpy=
array([[[[0]],

        [[0]],

        [[0]]]], dtype=int32)>

In [ ]:
tf_rank_4[:,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=int32, numpy=
array([[[[0]]],


       [[[0]]]], dtype=int32)>

In [ ]:
rank_2_tensor = tf.constant([[1,2],
                             [3,4]])

In [ ]:
rank_2_tensor.shape,rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
#creating additional dimension
tf_expand_dim = rank_2_tensor[...,tf.newaxis]
tf_expand_dim

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
#Alternate way to addtional dime
tf.expand_dims(rank_2_tensor,axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

## Manipulating Tensors

### '+','-','*'.'/'

In [ ]:
tensor = tf.constant([[5,7],
                      [6,8]])

In [ ]:
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 17],
       [16, 18]], dtype=int32)>

In [ ]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-5, -3],
       [-4, -2]], dtype=int32)>

In [ ]:
tensor *10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 70],
       [60, 80]], dtype=int32)>

In [ ]:
tensor/10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.5, 0.7],
       [0.6, 0.8]])>

In [ ]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 70],
       [60, 80]], dtype=int32)>

In [ ]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 17],
       [16, 18]], dtype=int32)>

### Matrix multiplication
in ML, Matrix multiplication is common to tensor

There are two rules our tensors (or matrices) need to fulfill we are going to matrix multiplication:

1. Inner dimension should match
2. The resulting matrix has the shape of outer dimension

In [ ]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 67,  91],
       [ 78, 106]], dtype=int32)>

In [ ]:
tf.multiply(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 49],
       [36, 64]], dtype=int32)>

In [ ]:
#matrix multiplication python operator '@'

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 67,  91],
       [ 78, 106]], dtype=int32)>

In [ ]:
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
y = tf.constant([[10,11],
                 [12,13],
                 [14,15]])

In [ ]:
x @ y

InvalidArgumentError: ignored

In [ ]:
tf.matmul(x,y)

## ** Resources : ** Info and example of matrix multiplication https://www.mathsisfun.com/algebra/matrix-multiplying.html 

---



In [ ]:
tf.reshape(y,shape = (2,3))

In [ ]:
x.shape,tf.reshape(y,shape = (2,3)).shape

In [ ]:
x @ tf.reshape(y,shape = (2,3))

In [ ]:
tf.matmul(x,tf.reshape(y, shape = (2,3)))

In [ ]:
x,tf.transpose(x), tf.reshape(x,shape=(2,3))

In [ ]:
tf.matmul(tf.reshape(x,shape=(2,3)),y)               

In [ ]:
tf.matmul(tf.transpose(x),y)

### The dot product

#### <b>The matrix multiplication is also reffered as Dot product</b>

You can perform matrix multiplication using:

* tf.matmul()

* tf.tensordot()

In [ ]:
# perform dot matrix multiplication
tf.tensordot(x,tf.transpose(y),axes=1)

In [ ]:
# perform matrix multiplication between x and y (transpose)
tf.matmul(x,tf.transpose(y))

In [ ]:
#perform matrix multiplication b/w x and y (reshape)
tf.matmul(x,tf.reshape(y,shape=(2,3)))

Generally, when we performing matrix multiplication on two tensors and one of the axes doesn't line up,you will transpose(rather than reshape)of the tensor to get satisfy the matrix multiplication rules

## Typecast in tensor

In [ ]:
a = tf.constant([1.5,2.7])

In [ ]:
a.dtype

In [ ]:
b = tf.constant([5,7])

In [ ]:
b.dtype

In [ ]:
c = tf.cast(a,dtype=tf.float16)

In [ ]:
c.dtype

In [ ]:
d = tf.cast(b,dtype=tf.int16)
d.dtype

In [ ]:
e = tf.cast(a,dtype=tf.float64)
e.dtype

# Aggregating Tensor

Aggregating tensors = condencing them from the multiple values down to a smaller amount of values

In [ ]:
# get the abs value
h = tf.constant([-5,-9])

In [ ]:
#get the abs value
tf.abs(h)

let go through the following forms of aggregation
* get the minimum
* get the maximum
* get the mean of the tensor
* get the sum of the tensor

In [ ]:
import numpy as np
g = tf.constant(np.random.randint(0,100,size = 50))

In [ ]:
g

In [ ]:
#to find the min value
tf.reduce_min(g),np.min(g)

In [ ]:
#To find the max value
tf.reduce_max(g)

In [ ]:
#To find the mean value
tf.reduce_mean(g)

In [ ]:
#To find the sum value
tf.reduce_sum(g)

In [ ]:
#To find std
tf.math.reduce_std(tf.cast(g, dtype=tf.float16))

In [ ]:
#To find variance
tf.math.reduce_variance(tf.cast(g,dtype=tf.float16)) #wont work

In [ ]:
#if we need to find variance in tensorflow, tensorflow_probalility is used
#to find variance
import tensorflow_probability as tfd
tfd.stats.variance(g)

In [ ]:
#to find std
tfd.stats.stddev(tf.cast(g,dtype=tf.float32))

## Find the positional maximum and minimum 

In [ ]:
#To find positional max
tf.math.argmax(g)

In [ ]:
#to find positional min
tf.argmin(g)

## Squeezed in tensorflow

In [ ]:
i = tf.constant(tf.random.uniform(shape = [50]),shape=(1,1,1,1,50))
i

In [ ]:
i_squeezed = tf.squeeze(i)
i_squeezed

# One Hot encoder

In [ ]:
#createing a list

l1 = [0,1,2,3] #red,blue,green and yellow

In [ ]:
tf.one_hot(l1,depth=5)

In [ ]:
indices = [0, 2, -1, 1]
depth = 3
tf.one_hot(indices,depth, on_value=5.0, off_value=0.0)

In [ ]:
tf.one_hot(l1,depth=4,on_value="i love deep learing",off_value="i love RPA")

## Math function in tensorflow

In [ ]:
a = tf.range(10)

In [ ]:
a



In [ ]:
tf.sqrt(tf.cast(a,dtype= tf.float32))

In [ ]:
tf.square(a)

In [ ]:
tf.math.log(tf.cast(a,dtype=tf.float16))

In [ ]:
#angle
input = tf.constant([-2.25 + 4.75j, 3.25 + 5.75j], dtype=tf.complex64)

In [ ]:
tf.math.angle(input)

In [ ]:
#tanah
t = tf.constant([-float ("inf"),-1,-0.5,0,0.5,1,10,float ("inf")])

In [ ]:
#Tanh is the hyperbolic tangent function, which is the hyperbolic analogue of the Tan circular function used throughout trigonometry
tf.math.atanh(t)

In [ ]:
tf.tanh(t)

In [ ]:
tf.tan(t)

# Tensorflow and Numpy

In [ ]:
j = tf.constant(np.array([1,2,3]))
j

In [ ]:
#changeing tensor into numpy
np.array(j),type(np.array(j))

In [ ]:
j.numpy(),type(j.numpy())

In [ ]:
j =tf.constant([3.])
j.numpy()[0]

There are two main format we can save our's model's too

1. The savedModel Format
2. The HDF5 format

#Download a model (or any other files) from google colab

1. you can go the files and rigth click the file and download

2. Use code(see the cell below)

3. save it to google drive by connecting to google drive and copying it

In [ ]:
from google.colab import files
files.download("file_location")  

# larger problem

In [ ]:
#import libaries
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
# Read in the insurance dataset
insurance = pd.read_csv("https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv")
insurance

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
insurance.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [ ]:
#we need to convert object type to numeric data for that we using onehot encoder
df = pd.get_dummies(insurance)
df

age     bmi  ...  region_southeast  region_southwest
0      19  27.900  ...                 0                 1
1      18  33.770  ...                 1                 0
2      28  33.000  ...                 1                 0
3      33  22.705  ...                 0                 0
4      32  28.880  ...                 0                 0
...   ...     ...  ...               ...               ...
1333   50  30.970  ...                 0                 0
1334   18  31.920  ...                 0                 0
1335   18  36.850  ...                 1                 0
1336   21  25.800  ...                 0                 1
1337   61  29.070  ...                 0                 0

[1338 rows x 12 columns]

In [ ]:
df.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_female', 'sex_male',
       'smoker_no', 'smoker_yes', 'region_northeast', 'region_northwest',
       'region_southeast', 'region_southwest'],
      dtype='object')

In [ ]:
x = df.drop(["charges"],axis=1)
y = df["charges"]
x,y

(      age     bmi  ...  region_southeast  region_southwest
 0      19  27.900  ...                 0                 1
 1      18  33.770  ...                 1                 0
 2      28  33.000  ...                 1                 0
 3      33  22.705  ...                 0                 0
 4      32  28.880  ...                 0                 0
 ...   ...     ...  ...               ...               ...
 1333   50  30.970  ...                 0                 0
 1334   18  31.920  ...                 0                 0
 1335   18  36.850  ...                 1                 0
 1336   21  25.800  ...                 0                 1
 1337   61  29.070  ...                 0                 0
 
 [1338 rows x 11 columns], 0       16884.92400
 1        1725.55230
 2        4449.46200
 3       21984.47061
 4        3866.85520
            ...     
 1333    10600.54830
 1334     2205.98080
 1335     1629.83350
 1336     2007.94500
 1337    29141.36030
 Name: charges, Lengt

In [ ]:
#create x & y Values
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state = 42)

In [ ]:
x_train.shape,x_test.shape

((936, 11), (402, 11))

In [ ]:
#createing neural network
#creating input data
insurance = tf.keras.Sequential(
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1)
)
#compling
insurance.compile